import type { Metadata } from "next";
import "../(global)/globals.css";
import { Providers } from "../(global)/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}



// export default function AdminLayout({ children }: { children: React.ReactNode }) {
  // const user = useAuthStore((s) => s.user)
  // const router = useRouter()
  // useEffect(() => {
  //   if (!user?.roles.includes('Admin')) {
  //     router.replace('/403')
  //   }
  // }, [user])
  // useEffect(() => {
  //   if (!user) router.replace('/login')
  // }, [user])
//   return <>{children}</>
// }